export const MOSTRAR_FORMULARIO_CLIENTE = 'MOSTRAR_FORMULARIO_CLIENTE';
export const OCULTAR_FORMULARIO_CLIENTE = 'OCULTAR_FORMULARIO_CLIENTE';
export const VALIDAR_FORMULARIO_CLIENTE = 'VALIDAR_FORMULARIO_CLIENTE';
export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
