export const MOSTRAR_FORMULARIO_CLIENTE = 'MOSTRAR_FORMULARIO_CLIENTE';
export const OCULTAR_FORMULARIO_CLIENTE = 'OCULTAR_FORMULARIO_CLIENTE';
export const MOSTRAR_ALERTA_CLIENTE = 'MOSTRAR_ALERTA_CLIENTE';
export const OCULTAR_ALERTA_CLIENTE = 'OCULTAR_ALERTA_CLIENTE';
export const OBTENER_CLIENTES = 'OBTENER_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const CLIENTE_ACTUAL = 'CLIENTE_ACTUAL';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
export const CLIENTE_ERROR = 'CLIENTE_ERROR';

export const CARGOS_CLIENTE = 'CARGOS_CLIENTE';
export const AGREGAR_CARGO = 'AGREGAR_CARGO';
export const MOSTRAR_ALERTA_CARGO = 'MOSTRAR_ALERTA_CARGO';
export const OCULTAR_ALERTA_CARGO = 'OCULTAR_ALERTA_CARGO';
export const ELIMINAR_CARGO = 'ELIMINAR_CARGO';
export const CARGO_ACTUAL = 'CARGO_ACTUAL';
export const ACTUALIZAR_CARGO = 'ACTUALIZAR_CARGO';

export const PAGOS_CLIENTE = 'PAGOS_CLIENTE';
export const AGREGAR_PAGO = 'AGREGAR_PAGO';
export const MOSTRAR_ALERTA_PAGO = 'MOSTRAR_ALERTA_PAGO';
export const OCULTAR_ALERTA_PAGO = 'OCULTAR_ALERTA_PAGO';
export const ELIMINAR_PAGO = 'ELIMINAR_PAGO';
export const PAGO_ACTUAL = 'PAGO_ACTUAL';
export const ACTUALIZAR_PAGO = 'ACTUALIZAR_PAGO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';




